### ISSUE TITLE
URL 404

### ISSUE THREAD

**Issue by nicecube** [robinp7720/Blue-Stats-Minecraft#29]
Hi, i just install Stat3 and the new BlueStats release, i have some dificulty :(

Home page are working but when i clic on other tabs link or player i got a 404 error, i check all my url config in the blueStats-url everything look ok 

Could you help me to setup plz

http://minecraftquebec.ca/stats/       = Working
http://minecraftquebec.ca/stats/player/nicecube/        = Not Working

Nice day

**Comment by smc87** [comment]
I have this exact same issue...none of the links at the top work either, for example "highscores".

**Comment by smc87** [comment]
my site is hosted on */stats i changed the config in the .htacess to "RewriteBase /stats/"
This made the links work...but all point back to the www root :(

I also wonder if this is related to an error i get on step1.php of the installer. no assets folder or cache folder is found, so i have to create them manually in bluestats base directory.

**Comment by robinp7720** [comment]
Sorry for the late reply, but this is not fault of Blue Stats (Most likely).
This is the fault of a parent htaccess in your www root.

**Comment by smc87** [comment]
Hi robin, no problem on the late reply, im not the quickest either!
What does blue stats expect the parent htaccess to contain - currently i have no htaccess in the root at all.

Thanks

**Comment by robinp7720** [comment]
Ok, I thought you had an existing htaccess in the parent directory. The bug should be fixed in the latest commit

**Comment by daytonmills** [comment]
I have an existing .htaccess in my parent directory. Currently it is configured for wordpress.
What should I do in my situation?

**Comment by daytonmills** [comment]
Fixed it by adding 
`RewriteBase` /stats/

**Comment by smc87** [comment]
Hi, just retried with the latest build...still a problem for me. 

Is it something to do with themes not working? The CSS doesn't seem to apply correctly to the homepage (and i have to manually create assets/cache folder on installation).

**Comment by smc87** [comment]
Ahh in-fact it seems the css not working is due to rules in the root BlueStats .htaccess not working.
I guess this is only a problem if you are in a subdirectory?

**Comment by smc87** [comment]
actually...seems to be working now. I think i may have been getting mixed results as i was testing with bigBlue - which seems to throw 500 errors too.
